# Generated by Django 3.0.7 on 2020-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='promocode_generated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='promocode_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
